#!/usr/bin/env bash
# generate-spotlight.sh — Auto-generate monthly Community Spotlight from git history
set -euo pipefail

# Usage: ./scripts/generate-spotlight.sh [MONTH] [YEAR]
MONTH="${1:-$(date +%m)}"
YEAR="${2:-$(date +%Y)}"
REPO="${REPO:-chernistry/bernstein}"
START_DATE="${YEAR}-${MONTH}-01"

# Month name
MONTH_NAME=$(python3 -c "import calendar; print(calendar.month_name[int('$MONTH')])")

echo "# Community Spotlight — ${MONTH_NAME} ${YEAR}"
echo ""
echo "> Auto-generated on $(date -u +%Y-%m-%d)"
echo ""

# Get contributor stats
echo "## By the Numbers"
echo ""
echo "| Metric | This Month |"
echo "|--------|-----------|"

# Merged PRs
if command -v gh &>/dev/null; then
    PR_COUNT=$(gh pr list --repo "$REPO" --state merged --search "merged:${START_DATE}..${YEAR}-${MONTH}-31" --json number --jq '. | length' 2>/dev/null || echo "N/A")
    echo "| Merged PRs | ${PR_COUNT} |"
fi

# Stars and forks
STARS=$(gh api "repos/$REPO" --jq '.stargazers_count' 2>/dev/null || echo "N/A")
FORKS=$(gh api "repos/$REPO" --jq '.forks_count' 2>/dev/null || echo "N/A")
echo "| Total Stars | ${STARS} |"
echo "| Total Forks | ${FORKS} |"
echo ""

# Get top contributors
echo "## Top Contributors"
echo ""

if command -v gh &>/dev/null; then
    gh pr list --repo "$REPO" --state merged --search "merged:${START_DATE}..${YEAR}-${MONTH}-31" --limit 20 --json number,title,author --jq '.[] | select(.author.login != "chernistry" and .author.login != "app/dependabot") | "- **[@\(.author.login)](https://github.com/\(.author.login))** — \(.title) ([#\(.number)](https://github.com/'"$REPO"'/pull/\(.number)))"' 2>/dev/null
fi

echo ""
echo "---"
echo ""
echo "_Generated by \`scripts/generate-spotlight.sh\`. Credit: @alexanderxfgl-bit (#780)_"
